package com.croh.security;

public enum Permission {
    VIEW_PII,
    REVIEW_VERIFICATION,
    MANAGE_BLACKLIST,
    PUBLISH_EVENT,
    REVIEW_REGISTRATION,
    MANAGE_RESOURCE_POLICY,
    MANAGE_REWARD_FULFILLMENT,
    APPROVE_EXCEPTION_REOPEN,
    CONFIGURE_ALERT_RULES,
    EXPORT_REPORTS,
    RESET_PASSWORD,
    MANAGE_REWARDS,
    MANAGE_METRICS,
    MANAGE_REPORT_TEMPLATES,
    VIEW_AUDIT_LOGS,
    PUBLISH_RESOURCE,
    MANAGE_ROLE_APPROVALS,
    SELF_SERVICE
}
